import Head from "next/head";
import Navbar from "../components/navbar";
import Welcome from "../components/welcome";
import About from "../components/about";
import Projects from "../components/projects";
import Contact from "../components/contact";

import { PrismaClient } from "@prisma/client";

export async function getServerSideProps() {
    const prisma = new PrismaClient();
    const projects = await prisma.projects.findMany();
    return {
        props: {
            foundProjects: projects,
        },
    };
}

export default function Home({ foundProjects }) {
    console.log(foundProjects);
    return (
        <div>
            <Head>
                <title>Neus Garcia&apos;s Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Welcome />
            <About />
            <Projects projects={foundProjects} />
            <Contact />
        </div>
    );
}
