import Head from "next/head";
import Navbar from "../components/navbar";
import Welcome from "../components/welcome";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Neus Garcia&apos;s Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Welcome />
        </div>
    );
}
